# Generated by Django 3.0.2 on 2020-01-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_auto_20200116_0643'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Thread',
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
